---
title: "leg-cite Example"
filters:
  - leg-cite
---

This filter implements citation macros for United States House and Senate bills, resolutions, and amendments, as well as Presidential Nominations.

Given a short citation like `118hr8070` between curly brackets (a.k.a. braces &mdash; `{}`), the rendered Quarto document
will display a link to the bill, resolution, amendment, or nomination referenced by the citation on Congress.gov: {118hr8070}.

If I don't supply the Congress in the macro, `leg-cite` defaults to the current Congress, like so: {s100}.

Here are amendment examples from the 115th and 114th Congresses: {115hamdt1}, {114samdt5}.

Short versions of the above: {115ha1}, {114sa5}.

Curly brackets are necessary. Without them, you get the text of the short citation as you wrote it: 118hr8070.

{118samdt5} starts this sentence.

More examples:

- {hjres123}
- {114sres321}
- {93hconres99}
- {h4321}

Non-punctuating trailing characters:

- {104sconres43}etc.

Nominations:

- {pn345}
- can also write with all caps PN: {117PN123}
